# Install scikit-learn


`pip install scikit-learn`

# Pandas Basic

In [2]:
import pandas as pd

my_list = [('isaac', 60, 50),('julie', 90, 70),('alex', 30, 40)]
header = ['name','math score','english score']

                        # .from_records帶入data
df_from_list = pd.DataFrame.from_records(my_list, columns=header)

print('create dataframe from list')
print(df_from_list)


my_dict = \
[{'name':'isaac', 'math score':60,'english score':50},
{'name':'julie', 'math score':90,'english score':70},
{'name':'alex', 'math score':30,'english score':40}
]

df_from_dict = pd.DataFrame(my_dict, columns=['name', 'math score', 'english score'])

print('create dataframe from dict')
print(df_from_dict)

create dataframe from list
    name  math score  english score
0  isaac          60             50
1  julie          90             70
2   alex          30             40
create dataframe from dict
    name  math score  english score
0  isaac          60             50
1  julie          90             70
2   alex          30             40


In [7]:
# use pandas to read csv file
df = pd.read_csv('RegularSeasonCompactResults.csv')

# print first five row
print(df.head())

# print last five row
print(df.tail())

# statistics on the dataframe
print(df.describe())

# print max value of each column
print(df.max())

# print Wscore that is greater than 150
print(df[df['Wscore'] > 150])

# drop rows and reset index
df_drop_row = df.drop(df.index[0]) #把索引0那行刪掉
df_reset_index1 = df_drop_row.reset_index(drop=True) #重整索引
print(df_reset_index1.head())

# drop columns
df_drop_column = df.drop('Season', axis=1)  #刪欄
print(df_drop_column.head())

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0
        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0
              Season         Daynum          Wteam         Wscore  \
count  145289.000000  145289.000000  145289.000000  145289.000000   
mean     2001.574834      75.223816    1286.720646      76.600321   
std         9.233342      33.287418     104

In [3]:
df = pd.read_csv('RegularSeasonCompactResults.csv')

#想要多欄位
df_new = df[['Season', 'Daynum']]   
print(df_new.head())

# .to_csv存檔
df_new.to_csv('dfnew.csv', index=False)   
#df_new.to_csv('dfnew.csv', index=False, header=False)

#.apply把欄位所有值都帶入公式
df_daynum = df_new['Daynum'].apply(lambda x: 1 if x> 23 else 0) # if x>23 給他1
print(df_daynum.head())

   Season  Daynum
0    1985      20
1    1985      25
2    1985      25
3    1985      25
4    1985      25
0    0
1    1
2    1
3    1
4    1
Name: Daynum, dtype: int64


# Load CSV file

In [4]:
import pandas as pd

# load csv file
df = pd.read_csv('demo.csv')

# load csv file without header
# df = pd.read_csv('demo.csv', header=None)

# print dataframe
print(df)

# print dataframe shape
print(df.shape)

# print column
print(df['number_room'].values)  #只想看這欄的值

   size  number_room  house_price house_type
0  40.0          3.0          800        old
1  29.0          5.0          700      young
2  33.0          2.0          670      young
3   NaN          2.0          770        old
4   NaN          NaN          870      young
(5, 4)
[ 3.  5.  2.  2. nan]


# Numpy Basic

In [4]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"


<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.01697629 0.0697718 ]
 [0.58022408 0.21448915]]


ref: http://cs231n.github.io/python-numpy-tutorial/#numpy

# Missing value 遺失值處理
- inplace = True：不创建新的对象，直接对原始对象进行修改；
- inplace = False：对数据进行修改，创建并返回新的对象承载其修改结果。
- 默认是False，即创建新的对象进行修改，原对象不变，和深复制和浅复制有些类似。

In [6]:
import pandas as pd

# load csv file
df = pd.read_csv('demo.csv')
print(df)
print('=========================================')

#.dropna() 有缺失值的整行都丟掉
df_no_missing = df.dropna()  
print(df_no_missing)
print('=========================================')

#.fillna(補什麼 , inplace)
df["size"].fillna(df["size"].mean(), inplace=True)  
print(df)

   size  number_room  house_price house_type
0  40.0          3.0          800        old
1  29.0          5.0          700      young
2  33.0          2.0          670      young
3   NaN          2.0          770        old
4   NaN          NaN          870      young
   size  number_room  house_price house_type
0  40.0          3.0          800        old
1  29.0          5.0          700      young
2  33.0          2.0          670      young
   size  number_room  house_price house_type
0  40.0          3.0          800        old
1  29.0          5.0          700      young
2  33.0          2.0          670      young
3  34.0          2.0          770        old
4  34.0          NaN          870      young


## Encoding categorical features 把類別型(文字) 改成數字
- pd.Categorical(df['欄位']).codes
- .codes 會自己幫你排列 按英文字順序 從0開始給一個代表類別的數字

In [7]:
import pandas as pd

df = pd.read_csv('demo.csv')

print(df)  #發現有一欄是文字 沒辦法做計算
print('=========================================')

df['house_type'] = pd.Categorical(df['house_type']).codes
print(df)

   size  number_room  house_price house_type
0  40.0          3.0          800        old
1  29.0          5.0          700      young
2  33.0          2.0          670      young
3   NaN          2.0          770        old
4   NaN          NaN          870      young
   size  number_room  house_price  house_type
0  40.0          3.0          800           0
1  29.0          5.0          700           1
2  33.0          2.0          670           1
3   NaN          2.0          770           0
4   NaN          NaN          870           1


# CSV資料型別轉換 dataframe / numpy array 

In [9]:
import pandas as pd
import numpy as np

df = pd.read_csv('demo.csv')

#dataframe 轉為 numpy array
numpy_array = np.array(df)
print(numpy_array)

#numpy array 轉為 dataframe
df_from_numpy = pd.DataFrame(numpy_array)
print(df_from_numpy)

[[40.0 3.0 800 'old']
 [29.0 5.0 700 'young']
 [33.0 2.0 670 'young']
 [nan 2.0 770 'old']
 [nan nan 870 'young']]
      0    1    2      3
0  40.0  3.0  800    old
1  29.0  5.0  700  young
2  33.0  2.0  670  young
3   NaN  2.0  770    old
4   NaN  NaN  870  young


# train_test_split 資料分兩批 訓練/測試 

In [15]:
import numpy as np
from sklearn.model_selection import train_test_split

x, y = np.arange(20).reshape((10, 2)), np.arange(10)
print('x:',x)
print('y:',y)

print("shape of x:" ,x.shape)
print("shape of y:" ,y.shape)

print('=====================')

#train_test_split                                         訓練資料7成 測試資料3成 / random_state 取消隨機
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3,random_state=1)

print("x_train:",x_train) # X 訓練
print("x_test:",x_test)   # X 測試

print("y_train:" ,y_train) # Y 訓練
print("y_test:" ,y_test)   # Y 測試

x: [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
y: [0 1 2 3 4 5 6 7 8 9]
shape of x: (10, 2)
shape of y: (10,)
x_train: [[ 8  9]
 [ 0  1]
 [ 6  7]
 [ 2  3]
 [14 15]
 [16 17]
 [10 11]]
x_test: [[ 4  5]
 [18 19]
 [12 13]]
y_train: [4 0 3 1 7 8 5]
y_test: [2 9 6]


# preprocessing 資料預處理 
### z-score normalization
- 用z-score normalization取得標準差.平均值 ：preprocessing.StandardScaler().fit()
- 對數據進行標準化： .transform()

講義 P.19     normalization 
- ` .fit() 不會改變任何東西，在 建模.調參數 或 算統計變量時 會看到.fit() `

In [19]:
from sklearn import preprocessing
import numpy as np

x_train = np.array([[ 100., -1.,  2.],
                    [ 900.,  0.,  0.],
                    [ 200.,  1., -1.]])

#算平均.標準差 方法一：
print("mean of x_train:",x_train.mean(axis=0))
print("std of x_train:",x_train.std(axis=0))

#算平均.標準差 方法二：
scaler = preprocessing.StandardScaler().fit(x_train)  # .StandardScaler會去算平均標準差 z-score normalization

print("mean of x_scale:",scaler.mean_)
print("std of x_scale:",scaler.scale_)

# 用平均值和標準差 對數據進行標準化
x_train = scaler.transform(x_train) # .transform 壓在-1~1之間

print("============after standardiztion===========")

print('x_train:',x_train)

x_test = np.array([[-1., 1., 0.]])

x_test = scaler.transform(x_test)  #[重點]用 x_train的平均值.標準差 再對 x_test做標準化
print('x_test:',x_test)

mean of x_train: [4.00000000e+02 0.00000000e+00 3.33333333e-01]
std of x_train: [355.9026084    0.81649658   1.24721913]
mean of x_scale: [4.00000000e+02 0.00000000e+00 3.33333333e-01]
std of x_scale: [355.9026084    0.81649658   1.24721913]
============after standardiztion===========
x_train: [[-0.84292723 -1.22474487  1.33630621]
 [ 1.40487872  0.         -0.26726124]
 [-0.56195149  1.22474487 -1.06904497]]
x_test: [[-1.12671273  1.22474487 -0.26726124]]


### min-max normalization
- 用min-max normalization取得平均值.標準差 ： preprocessing.MinMaxScaler().fit()
- 對數據進行標準化： .transform()

In [20]:
from sklearn import preprocessing
import numpy as np

x_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

scaler = preprocessing.MinMaxScaler().fit(x_train) #.MinMaxScaler 會算 min-max normalization

# 用平均值和標準差 對數據進行標準化
x_train = scaler.transform(x_train) #壓在0~1之間

print('x_train:',x_train)

x_test = np.array([[ -3., -1.,  4.]])

x_test = scaler.transform(x_test)  #[重點] 用 x_train的平均值.標準差 再對 x_test做標準化
print('x_test:',x_test)

x_train: [[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]
x_test: [[-1.5         0.          1.66666667]]


# Evaluate Result 評估結果(衡量模型好壞)
P.23

In [22]:
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix

y_test = [0, 1, 0 , 1, 0]
y_pred = [1, 0, 0 , 1, 0]

#回歸的問題 用mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)  

#分類的問題 用accuracy_score, confusion_matrix
accuracy = accuracy_score(y_test, y_pred) #準確度
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False) #normalize=False(回傳猜對幾個樣本)
con_matrix = confusion_matrix(y_test, y_pred) #混淆矩陣


print("Mean squared error:",mse)
print('r2 score:',r2)

print('accuracy:',accuracy)
print('number of correct sample:',num_correct_samples)
print('confusion matrix:',con_matrix)

Mean squared error: 0.4
r2 score: -0.6666666666666665
accuracy: 0.6
number of correct sample: 3
confusion matrix: [[2 1]
 [1 1]]


## Kaggle Introduction

kaggle website: https://www.kaggle.com/  
kaggle api: https://github.com/Kaggle/kaggle-api

# 練習
- read student-mat.csv 讀檔
- change "sex" column to number 改變欄位內容
1. if sex = F → change sex = 1
2. if sex = M → change sex = 0
- filter out age is < 17 過濾
- save final dataframe to a csv file 存檔

In [5]:
import pandas as pd

df = pd.read_csv('./dataset/student-mat.csv')
# print(df.head())

df['sex'] = df['sex'].apply(lambda x: 1 if x =='F' else 0)  # if x="F" 就給值1  

df = df[df['age']<=16] #df ['條件']

df.to_csv('./01練習.csv')

  school  sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
2     GP    1   15       U     LE3       T     1     1   at_home     other   
3     GP    1   15       U     GT3       T     4     2    health  services   
4     GP    1   16       U     GT3       T     3     3     other     other   
5     GP    0   16       U     LE3       T     4     3  services     other   
6     GP    0   16       U     LE3       T     2     2     other     other   

   ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
2  ...      4        3      2     2     3      3       10   7   8  10  
3  ...      3        2      2     1     1      5        2  15  14  15  
4  ...      4        3      2     1     2      5        4   6  10  10  
5  ...      5        4      2     1     2      5       10  15  15  15  
6  ...      4        4      4     1     1      3        0  12  12  11  

[5 rows x 33 columns]
