#### 把照片 分格子 變成向量
![alt text](./images/ML_01.jpg)

![alt text](./images/ML_02.jpg)

![alt text](./images/ML_03.jpg)

![alt text](./images/ML_04.jpg)

In [1]:
import cv2
import numpy as np

s='./data/'  

num=100  #總共100張
row=240  #size
col=240 
images = np.zeros((num,row,col)) #先創圖片為空矩陣

n=0 #第幾張
for i in range(0,10):
    for j in range(1,11):
        images[n,:,:]=cv2.imread(s+str(i)+'/'+str(i)+'-'+str(j)+'.bmp',0)
        n=n+1

print(images.shape)  

(100, 240, 240)


In [2]:
#把每張240*240大小的圖從一整張，分割成6*6=36格
feature = np.zeros((num,round(row/40),round(col/40))) 

#依據黑色出現次數 為每個格子填上數值
for ni in range(0,num):
    for nr in range(0,row):
        for nc in range(0,col):
            if images[ni,nr,nc]==0:  #0是黑色
                feature[ni,int(nr/40),int(nc/40)]+=1

#把照片 向量化
dataset = feature[:,:].reshape(-1,round(row/40)*round(col/40)).astype(np.float32) 

# 圖片的標籤 (10張0、10張1...)
labels = np.asarray([int(i/10)  for i in range(0,100)])

print(feature[0])  #0的第一張圖
print(dataset.shape) #100張 每張36個數 的向量
print(labels.shape)
print(labels)

[[  0.   0. 178. 286.   6.   0.]
 [  0.   0. 333.  22. 320.   0.]
 [  0.   0. 291.   0. 285.   0.]
 [  0.   0. 361. 151. 284.   0.]
 [  0.   0.   4. 171.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
(100, 36)
(100,)
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3
 3 3 3 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 7 7 7 7
 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9]


In [3]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import neighbors
from sklearn.metrics import accuracy_score, confusion_matrix


X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.4)

print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

print(y_train)

(60, 36)
(60,)
(40, 36)
(40,)
[0 7 3 5 4 0 1 3 4 6 2 6 9 3 5 8 1 8 9 9 8 7 9 2 8 2 4 8 0 1 9 1 5 2 2 6 5
 6 8 3 0 5 1 6 8 5 9 4 1 2 9 0 3 3 6 1 7 7 7 3]


In [4]:
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

model = neighbors.KNeighborsClassifier(n_neighbors=10)
model.fit(X_train, y_train)


X_test = scaler.transform(X_test)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False)
con_matrix = confusion_matrix(y_test, y_pred)

print(y_test)
print(y_pred)
print('number of correct sample:',num_correct_samples)
print('accuracy:',accuracy)
print('confusion matrix:',con_matrix)

[4 0 4 7 3 5 5 8 5 7 6 8 2 5 0 4 4 1 9 0 1 9 0 1 7 2 3 6 6 2 0 7 6 7 3 9 2
 4 4 8]
[4 0 4 9 3 5 3 8 8 9 6 8 1 3 0 1 4 1 2 0 1 9 0 1 9 2 6 1 6 1 0 7 6 7 3 9 2
 4 4 8]
number of correct sample: 28
accuracy: 0.7
confusion matrix: [[5 0 0 0 0 0 0 0 0 0]
 [0 3 0 0 0 0 0 0 0 0]
 [0 2 2 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 1 0 0 0]
 [0 1 0 0 5 0 0 0 0 0]
 [0 0 0 2 0 1 0 0 1 0]
 [0 1 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 3]
 [0 0 0 0 0 0 0 0 3 0]
 [0 0 1 0 0 0 0 0 0 2]]
